### PR TITLE
Update to xdebug 2.7

### PR DESCRIPTION
**Pull request by nick-zh**
Trying to help with https://github.com/swoole/swoole-src/issues/2655

I merged xdebug 2.7 into the branch, while building i get this now:

```
/root/sdebug/xdebug.c: In function 'xdebug_execute_ex':
/root/sdebug/php_xdebug.h:347:20: error: ISO C90 forbids mixed declarations and code [-Werror=declaration-after-statement]
 #define GET_CUR_XG sw_zend_xdebug_globals *current_xdebug_globals = get_current_context();
                    ^~~~~~~~~~~~~~~~~~~~~~
/root/sdebug/xdebug.c:1765:2: note: in expansion of macro 'GET_CUR_XG'
  GET_CUR_XG;
  ^~~~~~~~~~
/root/sdebug/xdebug.c:1767:2: error: ISO C90 forbids mixed declarations and code [-Werror=declaration-after-statement]
  zend_op_array        *op_array = &(execute_data->func->op_array);
  ^~~~~~~~~~~~~
In file included from /root/sdebug/xdebug.c:52:
/root/sdebug/xdebug.c: In function 'xdebug_execute_internal':
/root/sdebug/php_xdebug.h:347:20: error: ISO C90 forbids mixed declarations and code [-Werror=declaration-after-statement]
 #define GET_CUR_XG sw_zend_xdebug_globals *current_xdebug_globals = get_current_context();
                    ^~~~~~~~~~~~~~~~~~~~~~
/root/sdebug/xdebug.c:2032:2: note: in expansion of macro 'GET_CUR_XG'
  GET_CUR_XG;
  ^~~~~~~~~~
/root/sdebug/xdebug.c:2033:2: error: ISO C90 forbids mixed declarations and code [-Werror=declaration-after-statement]
  zend_execute_data    *edata = EG(current_execute_data);
  ^~~~~~~~~~~~~~~~~
cc1: all warnings being treated as errors
make: *** [Makefile:226: xdebug.lo] Error 1

```

I am sure this is not hard to fix, but i don't have C knowledge @mabu233 do you know how i could fix that?

### CODE REVIEW

**Comment by mabu233** [comment]
I don't have a 7.3 env, you try first :)
[https://github.com/mabu233/sdebug/tree/sdebug_2_7](https://github.com/mabu233/sdebug/tree/sdebug_2_7)
php_version must be >= php-7.3.0beta1
phpstorm 2019

**Comment by nick-zh** [comment]
@mabu233 awesome stuff, works like a charm, thank you so much!

**Comment by cesardraw2** [comment]
> Eu não tenho um env 7.3, você tenta primeiro :) 
> https://github.com/mabu233/sdebug/tree/sdebug_2_7
> php_version deve ser> = php-7.3.0beta1 
> phpstorm 2019

Run Perfect!

PHP 7.2.7-0ubuntu0.18.04.2 (cli) (built: Jul  4 2018 16:55:24) ( NTS )
Copyright (c) 1997-2018 The PHP Group
Zend Engine v3.2.0, Copyright (c) 1998-2018 Zend Technologies
    with Sdebug v2.7.3-dev, Copyright (c) 2002-2019, by Derick Rethans
    with Zend OPcache v7.2.7-0ubuntu0.18.04.2, Copyright (c) 1999-2018, by Zend Technologies

**Comment by danielesk** [comment]
@mabu233 **sdebug**与**swoole**发布的版本有绑定关系吗？？？

**Comment by lihe6666** [comment]
Think you very much! resolved

**Pull request closed without merging**
