### PR TITLE
Master

### PR DESCRIPTION
**Pull request by nick-zh**
merging master of xdebug into sdebug
if you merge this, could you also create an sdebug_2_9 branch from it, so i can move #2 to this new branch?

### CODE REVIEW

**Comment by nick-zh** [comment]
@mabu233 any update on this, i would really like to help to add `php:7.4` support after this is merged

**Comment by Millyn** [comment]
@nick-zh can you fork this repo , and start a new driven?

**Comment by nick-zh** [comment]
@Millyn swoole has already created a fork ✌️

**Comment by Millyn** [comment]
repo --> https://github.com/swoole/sdebug

**Pull request closed without merging**
